name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy .env.test to .env
      run: cp .env.test .env
    - name: Install Dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress
    - name: Set Environment to Test
      run: echo "DB_CONNECTION=sqlite" >> .env
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run Migrations and Seed
      run: php artisan migrate:fresh --seed --force
    - name: Execute tests (Unit and Feature tests)
      run: php artisan test
