name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Set Environment Variables
      run: |
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=database/database.sqlite" >> .env
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.test', '.env');"

    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        ls -lah database/  # Debug: Ensure database file is created

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Debug Database Tables
      run: php artisan migrate:status  # Debugging: Check if tables exist
      
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Tests
      run: php artisan test
